### ISSUE TITLE
Make `-r` optional

### ISSUE THREAD

**Issue by hahanein** [falood/file_system#12]
Is there a reason why option `-r` is not optional? I'd like to use exfswatch without it.

**Comment by falood** [comment]
I'll do it soon 🙂

**Comment by falood** [comment]
exfswatch depends on [fs](https://github.com/synrc/fs)
I checked the code of `fs`, I can only make it for `linux` and `windows`, because there's no `-r` option for `mac` and `freebsd`.
I don't think `fs` will provide it soon, so you'd better do it within your callback for now.
I'll keep an eye on fs about such feature.
