### ISSUE TITLE
Comparison to fs

### ISSUE THREAD

**Issue by lpil** [falood/file_system#43]
Hello!

Could you please document why one might want to use (or migrate to) this library over fs?

Thanks,
Louis

**Comment by falood** [comment]
I'm so sorry to missed this issue for a long time, I notified that you have switched to file_system for your mix-test.watch project.
I did this wrapper because fs is make with purge erlang, it's not really compatible when Erlang or Elixir version upgraded, and also fixed some issue when did hot upgrade.
